import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const SUPABASE_URL = 'https://YOUR-PROJECT.supabase.co';
const SUPABASE_ANON_KEY = 'YOUR_PUBLIC_ANON_KEY';
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
const state = { items:[], filtered:[], categories:[], selectedCategory:'Tutte', search:'', sort:'alpha', onlyAvailable:false, onlyNew:false, priceMax:null, role:'guest' };
function parseItNumber(v){ if(v==null) return null; if(typeof v==='number') return v; const s=String(v).trim().replace(/\./g,'').replace(',','.'); const n=parseFloat(s); return isNaN(n)?null:n; }
function formatPriceEUR(n){ if(n==null||isNaN(n)) return '—'; return n.toLocaleString('it-IT',{style:'currency',currency:'EUR'}); }
document.addEventListener('DOMContentLoaded', async ()=>{ document.getElementById('year').textContent = new Date().getFullYear(); setupUI(); await restoreSession(); await renderAuthState(); if(state.role!=='guest'){ await fetchProducts(); applyFilters(); } });
function setupUI(){ const $=id=>document.getElementById(id);
  $('#searchInput').addEventListener('input',e=>{state.search=e.target.value;applyFilters()});
  $('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;applyFilters()});
  $('#filterDisponibile').addEventListener('change',e=>{state.onlyAvailable=e.target.checked;applyFilters()});
  $('#filterNovita').addEventListener('change',e=>{state.onlyNew=e.target.checked;applyFilters()});
  $('#filterPriceMax').addEventListener('input',e=>{state.priceMax=parseItNumber(e.target.value);applyFilters()});
  document.getElementById('btnPublish').addEventListener('click',()=>{ if(state.role!=='admin') return alert('Solo admin'); alert('Hook pubblicazione pronto: collega Edge Function'); });
}
async function restoreSession(){ const { data:{ session } } = await supabase.auth.getSession(); if(session?.user){ const { data: prof } = await supabase.from('profiles').select('role').eq('id', session.user.id).single(); state.role = (prof?.role==='admin')?'admin':'agent'; } else { state.role='guest'; } supabase.auth.onAuthStateChange(async (_e,sess)=>{ if(sess?.user){ const { data: prof } = await supabase.from('profiles').select('role').eq('id', sess.user.id).single(); state.role=(prof?.role==='admin')?'admin':'agent'; await renderAuthState(); await fetchProducts(); applyFilters(); } }); }
async function renderAuthState(){ const logged = state.role!=='guest'; const ids=['btnLogin','btnLogout']; document.getElementById('btnLogin').classList.toggle('hidden',logged); document.getElementById('btnLogout').classList.toggle('hidden',!logged); document.getElementById('adminBox').hidden = (state.role!=='admin'); document.getElementById('resultInfo').textContent = logged?'Caricamento listino…':'Accedi per visualizzare il listino.'; }
async function fetchProducts(){ const { data, error } = await supabase.from('products').select('id,codice,descrizione,categoria,sottocategoria,prezzo,unita,disponibile,novita,pack,pallet,tags,updated_at, product_media(id,kind,path,sort)').order('descrizione',{ascending:true}); if(error){ document.getElementById('resultInfo').textContent='Errore: '+error.message; return; } const items=[]; for(const p of data){ const media=p.product_media||[]; const images=[]; for(const m of media.filter(x=>x.kind==='image').sort((a,b)=>(a.sort??0)-(b.sort??0))){ const { data: blobData } = await supabase.storage.from('media').download(m.path); if(blobData){ const url=URL.createObjectURL(blobData); images.push(url);} } const video = media.find(x=>x.kind==='video')?.path || null; let videoUrl=null; if(video){ const { data: vBlob } = await supabase.storage.from('media').download(video); if(vBlob) videoUrl=URL.createObjectURL(vBlob); } items.push({ codice:p.codice, descrizione:p.descrizione, categoria:p.categoria, sottocategoria:p.sottocategoria, prezzo:p.prezzo, unita:p.unita, disponibile:p.disponibile, novita:p.novita, pack:p.pack, pallet:p.pallet, tags:p.tags||[], img:images[0]||'', img2:images[1]||'', img3:images[2]||'', video:videoUrl, updated_at:p.updated_at }); } state.items=items; buildCategories(); applyFilters(); document.getElementById('resultInfo').textContent = `${items.length} articoli`; }
function buildCategories(){ const set=new Set(state.items.map(p=>p.categoria||'Senza categoria')); state.categories=['Tutte',...Array.from(set).sort((a,b)=>a.localeCompare(b,'it'))]; const box=document.getElementById('categoryList'); box.innerHTML=''; state.categories.forEach(cat=>{ const b=document.createElement('button'); b.className='tag hover:bg-slate-100'; b.textContent=cat; b.addEventListener('click',()=>{state.selectedCategory=cat;applyFilters()}); box.appendChild(b); }); }
function applyFilters(){ const grid=document.getElementById('productGrid'); grid.innerHTML=''; let arr=[...state.items]; if(state.selectedCategory!=='Tutte') arr=arr.filter(p=>p.categoria===state.selectedCategory); if(state.search){ const q=state.search.toLowerCase(); arr=arr.filter(p=>(p.codice+' '+p.descrizione+' '+p.tags.join(' ')).toLowerCase().includes(q)); } if(state.onlyAvailable) arr=arr.filter(p=>p.disponibile); if(state.onlyNew) arr=arr.filter(p=>p.novita); if(state.priceMax!=null) arr=arr.filter(p=>p.prezzo!=null && p.prezzo<=state.priceMax); switch(state.sort){ case 'priceAsc': arr.sort((a,b)=>(a.prezzo??Infinity)-(b.prezzo??Infinity)); break; case 'priceDesc': arr.sort((a,b)=>(b.prezzo??-Infinity)-(a.prezzo??-Infinity)); break; case 'newest': arr.sort((a,b)=>(b.updated_at||'').localeCompare(a.updated_at||'')); break; default: arr.sort((a,b)=> a.descrizione.localeCompare(b.descrizione,'it')); } if(!arr.length){ grid.innerHTML='<div class="col-span-full text-center text-slate-500 py-10">Nessun articolo trovato.</div>'; return; } for(const p of arr){ const card=document.createElement('article'); card.className='card rounded-2xl bg-white border shadow-sm overflow-hidden'; card.innerHTML=`<div class="aspect-square bg-slate-100 grid place-content-center">${p.img?`<img src="${p.img}" alt="${p.descrizione}" class="w-full h-full object-contain">`:`<div class="text-slate-400">Nessuna immagine</div>`}</div><div class="p-3 space-y-2"><div class="flex items-start justify-between gap-2"><h3 class="font-medium leading-snug line-clamp-2">${p.descrizione}</h3>${p.novita?'<span class="tag bg-emerald-50 text-emerald-700 border-emerald-200">Novità</span>':''}</div><p class="text-xs text-slate-500">${p.codice}</p><div class="flex items-center justify-between"><div class="text-lg font-semibold">${formatPriceEUR(p.prezzo)}</div><button class="rounded-xl border px-3 py-1.5 text-sm hover:bg-slate-50">Vedi</button></div><div class="flex gap-1 flex-wrap">${p.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div>`; card.querySelector('button').addEventListener('click',()=>alert(p.descrizione+"\nPrezzo: "+formatPriceEUR(p.prezzo))); grid.appendChild(card); } }
